# Generated by Django 6.0.6 on 2026-09-26 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('ADOCAO', 'Adoção'), ('PERDIDO', 'Animal Perdido')], default='ADOCAO', max_length=10, verbose_name='Tipo de Serviço')),
                ('tipo_animal', models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato'), ('OUTRO', 'Outro')], default='CACHORRO', max_length=15, verbose_name='Tipo de Animal')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Pet')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='Estado (UF)')),
                ('cidade', models.CharField(default='', max_length=100, verbose_name='Cidade')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone de contato do tutor')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição / Informações extras')),
                ('imagem', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL da Foto do animal')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ADOTADO', 'Adotado'), ('PERDIDO', 'Perdido'), ('ENCONTRADO', 'Encontrado'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=15, verbose_name='Status do Anúncio')),
                ('raca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indeterminado')], max_length=1, null=True)),
                ('idade_aproximada', models.CharField(blank=True, choices=[('Filhote', 'Filhote'), ('Adulto', 'Adulto'), ('Idoso', 'Idoso')], max_length=10, null=True)),
                ('medicamento', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não sei', 'Não sei')], max_length=10, null=True)),
                ('vacinacao', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não sei', 'Não sei')], max_length=10, null=True)),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Último local visto / Ponto de referência')),
                ('inativado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de inativação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animais', to=settings.AUTH_USER_MODEL, verbose_name='Tutor Anunciante')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-created_at'],
            },
        ),
    ]
