# Generated by Django 6.0.5 on 2026-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indeterminado')], max_length=1)),
                ('idade_aproximada', models.CharField(choices=[('Filhote', 'Filhote'), ('Adulto', 'Adulto'), ('Idoso', 'Idoso')], max_length=10)),
                ('medicamento', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao'), ('Nâo sei', 'Nao Sabe')], max_length=10)),
                ('vacinacao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao'), ('Nâo sei', 'Nao Sabe')], max_length=10)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('raca', models.CharField(blank=True, max_length=50, null=True, verbose_name='raça')),
                ('contato', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['nome'],
            },
        ),
    ]
