# Generated by Django 6.0.6 on 2026-06-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('raca', models.CharField(blank=True, max_length=50, null=True, verbose_name='raça')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indeterminado')], max_length=1)),
                ('idade', models.CharField(blank=True, max_length=2, null=True)),
                ('idade_aproximada', models.CharField(choices=[('Filhote', 'Filhote'), ('Adulto', 'Adulto'), ('Idoso', 'Idoso')], max_length=10)),
                ('medicamentos', models.CharField(choices=[('Sim', 'Sim'), ('NaoNão', 'Nao'), ('Nao sei', 'Não sei')], max_length=10)),
                ('vacinacao', models.CharField(choices=[('Sim', 'Sim'), ('NaoNão', 'Nao'), ('Nao sei', 'Não sei')], max_length=10, verbose_name='vacinação')),
                ('contato', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['nome'],
            },
        ),
    ]
