# Generated by Django 6.0.6 on 2026-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='imagem',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL da Foto do animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='contato',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='medicamento',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não sei', 'Não sei')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacinacao',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não sei', 'Não sei')], max_length=10),
        ),
    ]
