# Generated by Django 6.0.6 on 2026-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='telefone_contato',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone de contato do tutor (cache/fallback)'),
        ),
    ]
