# Generated by Django 6.0.6 on 2026-09-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de contato do tutor'),
        ),
    ]
