# Generated by Django 6.0.6 on 2026-09-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animal_telefone_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='telefone_contato',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone de contato do tutor'),
        ),
    ]
