# Generated by Django 6.0.6 on 2026-09-19 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animal_descricao_animal_imagem_alter_animal_contato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='contato',
        ),
        migrations.AddField(
            model_name='animal',
            name='cidade',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='animal',
            name='inativado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de inativação'),
        ),
        migrations.AddField(
            model_name='animal',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Último local visto / Ponto de referência'),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ADOTADO', 'Adotado'), ('PERDIDO', 'Perdido'), ('ENCONTRADO', 'Encontrado'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=15, verbose_name='Status do Anúncio'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo_animal',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato'), ('OUTRO', 'Outro')], default='CACHORRO', max_length=15, verbose_name='Tipo de Animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo_servico',
            field=models.CharField(choices=[('ADOCAO', 'Adoção'), ('PERDIDO', 'Animal Perdido')], default='ADOCAO', max_length=10, verbose_name='Tipo de Serviço'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animais', to=settings.AUTH_USER_MODEL, verbose_name='Tutor Anunciante'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição / Informações extras'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_aproximada',
            field=models.CharField(blank=True, choices=[('Filhote', 'Filhote'), ('Adulto', 'Adulto'), ('Idoso', 'Idoso')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='medicamento',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não sei', 'Não sei')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indeterminado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacinacao',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não sei', 'Não sei')], max_length=10, null=True),
        ),
    ]
