# Generated by Django 6.0.5 on 2026-07-08 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_cnae_principal_remove_usuario_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cpf',
        ),
    ]
