# Generated by Django 6.0.6 on 2026-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarios_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
