# Generated by Django 6.0.6 on 2026-09-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_pessoafisica_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / WhatsApp'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_validado',
            field=models.BooleanField(default=False, verbose_name='WhatsApp Validado'),
        ),
    ]
