# Generated by Django 6.0.6 on 2026-09-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_telefone_usuario_telefone_validado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cpf',
        ),
    ]
