# Generated by Django 6.0.6 on 2026-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_pessoafisica_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone / WhatsApp'),
        ),
    ]
