# Generated by Django 6.0.6 on 2026-09-07 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDesaparecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Animal')),
                ('local', models.CharField(max_length=200, verbose_name='Último local visto')),
                ('contato', models.CharField(max_length=50, verbose_name='Contato do Tutor')),
                ('descricao', models.TextField(verbose_name='Descrição do Animal')),
                ('foto', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL da Foto')),
                ('encontrado', models.BooleanField(default=False, verbose_name='Já foi encontrado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
            ],
            options={
                'verbose_name': 'Animal Desaparecido',
                'verbose_name_plural': 'Animais Desaparecidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.TextField(verbose_name='Resumo / Subtítulo')),
                ('conteudo', models.TextField(blank=True, verbose_name='Conteúdo Completo')),
                ('imagem', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Nome do Autor')),
                ('texto', models.TextField(max_length=1000, verbose_name='Texto do Post')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunidade_posts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Post da Comunidade',
                'verbose_name_plural': 'Posts da Comunidade',
                'ordering': ['-created_at'],
            },
        ),
    ]
