# Generated by Django 6.0.6 on 2026-09-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalDesaparecido',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
