# Generated by Django 6.0.5 on 2026-06-17 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ongs', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusAdocao', models.CharField(choices=[('A', 'Aberta'), ('F', 'Finalizada'), ('C', 'Cancelada'), ('I', 'Inativa')], default='A', max_length=1)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('raca', models.CharField(blank=True, max_length=50, null=True, verbose_name='adoção')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indeterminado')], max_length=1)),
                ('idade', models.CharField(blank=True, max_length=2, null=True)),
                ('idade_aproximada', models.CharField(choices=[('Filhote', 'Filhote'), ('Adulto', 'Adulto'), ('Idoso', 'Idoso')], max_length=10)),
                ('medicamentos', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao'), ('Nâo sei', 'Nao Sabe')], max_length=10)),
                ('vacinacao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao'), ('Nâo sei', 'Nao Sabe')], max_length=10)),
                ('contato', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ongs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ongs.ong')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'Adoçao',
                'verbose_name_plural': 'Adoções',
                'ordering': ['nome'],
            },
        ),
    ]
