# Generated by Django 6.0.5 on 2026-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusAdocao', models.CharField(choices=[('A', 'Aberta'), ('F', 'Finalizada'), ('C', 'Cancelada'), ('I', 'Inativa')], default='A', max_length=1, verbose_name='Status da Adoção')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indeterminado')], max_length=1, verbose_name='Sexo do animal')),
                ('idade_aproximada', models.CharField(choices=[('Filhote', 'Filhote'), ('Adulto', 'Adulto'), ('Idoso', 'Idoso')], max_length=10, verbose_name='Idade aproximada do animal')),
                ('medicamentos', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao'), ('Nâo sei', 'Nao Sabe')], max_length=10, verbose_name='O animal faz uso de medicamentos?')),
                ('vacinacao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Nao'), ('Nâo sei', 'Nao Sabe')], max_length=10, verbose_name='O animal está com a vacinação em dia?')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do animal')),
                ('raca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça do animal')),
                ('contato', models.CharField(max_length=15)),
                ('descricao', models.TextField(help_text='Descreva o animal, incluindo informações sobre seu comportamento, saúde e necessidades especiais.Quanto mais detalhes você fornecer, melhor será a experiência do adotante.', max_length=500, verbose_name='Descrição do animal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adoçao',
                'verbose_name_plural': 'Adoções',
                'ordering': ['nome'],
            },
        ),
    ]
