# Generated by Django 6.0.6 on 2026-09-07 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0001_initial'),
        ('animais', '0002_animal_descricao_animal_imagem_alter_animal_contato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adocao',
            options={'ordering': ['-created_at'], 'verbose_name': 'Adoção', 'verbose_name_plural': 'Adoções'},
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='StatusAdocao',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='idade_aproximada',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='raca',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='vacinacao',
        ),
        migrations.AddField(
            model_name='adocao',
            name='adotante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adocoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Adotante'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adocoes', to='animais.animal', verbose_name='Animal'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='email_adotante',
            field=models.EmailField(default='', max_length=254, verbose_name='Email do Adotante'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='ja_teve_animais',
            field=models.CharField(default='Não', max_length=10, verbose_name='Já teve animais?'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='ja_vacinado',
            field=models.CharField(default='Sim', max_length=10, verbose_name='Manterá vacinação em dia?'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='motivacao',
            field=models.TextField(default='', verbose_name='Motivação / Sobre o adotante'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='nome_adotante',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Adotante'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='status',
            field=models.CharField(choices=[('A', 'Aberta'), ('P', 'Aprovada'), ('R', 'Recusada'), ('F', 'Finalizada'), ('C', 'Cancelada')], default='A', max_length=1, verbose_name='Status da Adoção'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='telefone_adotante',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone do Adotante'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
